name = "tc"
main = "src/index.js"
compatibility_date = "2024-03-07"
workers_dev = true
compatibility_flags = [ "nodejs_compat" ]

kv_namespaces = [
  { binding = "tc", id = "774d8e0cc2634f4581cf2e36e91d5d13" }
]

[triggers]
crons = ["*/15 13 * * mon-fri", "0-15/15 14 * * mon-fri" ]

[placement]
mode = "smart"

[observability]
enabled = true
